name: Script vm backup rsv-final

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the environment'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Prod
          - Dev

jobs:
  run-powershell-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0  # Ensure all files and folders are checked out

      - name: Checkout script repository
        uses: actions/checkout@v2
        with:
          repository: vivekcorp/scriptcall
          ref: main
          token: ${{ secrets.MY_GITHUB_PAT }}
          path: scriptcall  # Checkout in a separate folder

      - name: Install Az PowerShell Module
        run: |
          pwsh -Command 'Install-Module -Name Az -Force -AllowClobber -Scope CurrentUser'
          pwsh -Command 'Import-Module Az'
          
      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.PROD_ARM_CLIENT_ID }}","tenantId":"${{ secrets.PROD_ARM_TENANT_ID }}","clientSecret":"${{ secrets.PROD_ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}"}'

      - name: Print Environment Variables
        run: printenv

      - name: Debug - Check Files and Folders
        run: |
          echo "Listing all files in workspace..."
          ls -R $GITHUB_WORKSPACE
          
      - name: Debug - List Important Directories
        run: |
          echo "Checking GoldenImage folder..."
          ls -al $GITHUB_WORKSPACE/GoldenImage || echo "GoldenImage folder not found!"
          echo "Checking Script folder..."
          ls -al $GITHUB_WORKSPACE/scriptcall/Testing/script || echo "Script folder not found!"
          
      - name: Debug - Print Full Path to Script
        run: |
          echo "Full path to backup.ps1:"
          echo "${GITHUB_WORKSPACE}/scriptcall/Testing/script/backup.ps1"
          
      - name: Run PowerShell Script
        run: |
          Environment="${{ github.event.inputs.Environment }}"
          ParameterPath="${GITHUB_WORKSPACE}/GoldenImage/${Environment}_Parameterfile.json"
          ScriptPath="${GITHUB_WORKSPACE}/scriptcall/Testing/script/backup.ps1"
          echo "Running script: $ScriptPath with parameter: $ParameterPath"
          if [ -f "$ScriptPath" ]; then
            chmod +x "$ScriptPath"
            pwsh -Command "Connect-AzAccount -ServicePrincipal -TenantId '${{ secrets.PROD_ARM_TENANT_ID }}' -Credential (New-Object -TypeName 'System.Management.Automation.PSCredential' -ArgumentList '${{ secrets.PROD_ARM_CLIENT_ID }}', (ConvertTo-SecureString '${{ secrets.PROD_ARM_CLIENT_SECRET }}' -AsPlainText -Force))"
            pwsh -File "$ScriptPath" -ParameterPath "$ParameterPath"
          else
            echo "Script file not found: $ScriptPath"
            exit 1
          fi
        shell: bash
