name: Master Workflow

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Select the environment'
        required: true
        default: 'Prod'
        type: choice
        options:
          - Prod
          - Dev

jobs:
  Map-Network-Drive:
    uses: ./.github/workflows/file-share.yml
    secrets: inherit
    with:
      Environment: ${{ github.event.inputs.Environment }}

  Web-Install-IIS:
    needs: Map-Network-Drive
    uses: ./.github/workflows/web-iis-install.yml
    secrets: inherit
    with:
      Environment: ${{ github.event.inputs.Environment }}
